"""
Test Setup - Phase 1 & 2 of the new_feature_craft pipeline.

Phase 1: Analyze repo test infrastructure (framework, files, deps).
Phase 2: Generate run-tests.sh and validate it passes on the full repo.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import subprocess
from pathlib import Path
from typing import Dict, Optional

from agents.claude_code_executor import ClaudeCodeExecutor, setup_logger

logger = logging.getLogger(__name__)


class TestSetup:
    """Handles test analysis and run-tests.sh generation/validation."""

    def __init__(
        self,
        model: str,
        flash_model: str = "",
        test_timeout: int = 300,
    ):
        self.model = model
        self.flash_model = flash_model or model
        self.test_timeout = test_timeout

        # Load prompts
        prompts_dir = Path(__file__).parent / "config" / "prompts"
        self.analyze_prompt = self._load_prompt(prompts_dir / "analyze_repo_tests.txt")
        self.generate_prompt = self._load_prompt(prompts_dir / "generate_run_tests.txt")

    @staticmethod
    def _load_prompt(path: Path) -> str:
        if path.exists():
            return path.read_text(encoding="utf-8")
        logger.warning(f"Prompt not found: {path}")
        return ""

    # ------------------------------------------------------------------
    # Phase 1: Repo Test Analysis
    # ------------------------------------------------------------------

    async def analyze_repo(
        self,
        repo_path: Path,
        output_dir: Path,
        log: logging.Logger,
    ) -> Optional[Dict]:
        """
        Phase 1: Explore repo, build up environment, write setup.sh.

        The agent will:
        1. Explore repo structure and identify test framework
        2. Install dependencies, compile, fix errors
        3. Write setup.sh capturing all setup steps
        4. Determine testability

        Returns:
            Analysis dict with test_framework, is_testable, setup_sh_path, etc.
            None on failure.
        """
        phase_dir = output_dir / "phase1_analysis"
        phase_dir.mkdir(parents=True, exist_ok=True)

        prompt = self.analyze_prompt.format(repo_path=repo_path)

        executor = ClaudeCodeExecutor(
            work_dir=repo_path,
            output_dir=phase_dir,
            model=self.model,
            task_name="analyze_repo_tests",
            logger=log,
        )

        try:
            result = await executor.execute_with_json_retry(
                query=prompt,
                timeout=25200,
                max_retries=3,
                must_include_keys=["test_framework", "is_testable"],
            )

            if not result:
                log.error("Phase 1: agent returned no result")
                return None

            # Save analysis
            analysis_file = output_dir / "repo_analysis.json"
            analysis_file.write_text(
                json.dumps(result, indent=2, ensure_ascii=False),
                encoding="utf-8",
            )
            log.info(f"Repo analysis saved: framework={result.get('test_framework')}, "
                     f"testable={result.get('is_testable')}")

            # Run setup.sh if agent created it
            setup_sh = repo_path / "setup.sh"
            if setup_sh.exists():
                log.info("Running setup.sh generated by agent...")
                setup_result = subprocess.run(
                    ["bash", str(setup_sh)],
                    cwd=repo_path,
                    capture_output=True,
                    text=True,
                    timeout=600,
                    env={**os.environ, "DEBIAN_FRONTEND": "noninteractive"},
                )
                # Save setup.sh output
                setup_log = phase_dir / "setup_sh_output.log"
                setup_log.write_text(
                    setup_result.stdout + setup_result.stderr,
                    encoding="utf-8",
                )
                if setup_result.returncode != 0:
                    log.warning(f"setup.sh exited with code {setup_result.returncode}, "
                                f"continuing anyway")
                else:
                    log.info("setup.sh completed successfully")

                # Copy setup.sh to output
                (output_dir / "setup.sh").write_text(
                    setup_sh.read_text(encoding="utf-8"), encoding="utf-8"
                )
            else:
                log.info("No setup.sh generated by agent")

            return result

        except Exception as e:
            log.error(f"Phase 1 failed: {e}")
            return None
        finally:
            try:
                await executor.disconnect()
            except Exception:
                pass

    # ------------------------------------------------------------------
    # Phase 2: Generate run-tests.sh & Validate
    # ------------------------------------------------------------------

    async def generate_and_validate_tests(
        self,
        repo_path: Path,
        repo_analysis: Dict,
        output_dir: Path,
        log: logging.Logger,
        max_refine: int = 3,
    ) -> Optional[Path]:
        """
        Generate run-tests.sh using LLM, validate, and refine if needed.

        On test failure, feeds error log back to the same executor
        (continue_conversation=True) to let the agent fix run-tests.sh.
        Up to max_refine refinement rounds.

        Returns:
            Path to validated run-tests.sh, or None if all attempts fail.
        """
        phase_dir = output_dir / "phase2_test_setup"
        phase_dir.mkdir(parents=True, exist_ok=True)

        run_tests_path = output_dir / "run-tests.sh"
        repo_run_tests = repo_path / "run-tests.sh"

        # Generate initial run-tests.sh
        prompt = self.generate_prompt.format(
            repo_path=repo_path,
            repo_analysis=json.dumps(repo_analysis, indent=2, ensure_ascii=False),
            test_timeout=self.test_timeout,
        )

        executor = ClaudeCodeExecutor(
            work_dir=repo_path,
            output_dir=phase_dir,
            model=self.model,
            task_name="generate_run_tests",
            logger=log,
        )

        try:
            result = await executor.execute_with_json_retry(
                query=prompt,
                timeout=25200,
                max_retries=3,
                must_include_keys=["run_tests_sh"],
            )

            if not result:
                log.error("Failed to generate run-tests.sh")
                return None

            # Write run-tests.sh
            self._write_run_tests(result["run_tests_sh"], run_tests_path, repo_run_tests, log)

            # Validate + refine loop
            for attempt in range(1 + max_refine):
                label = "initial" if attempt == 0 else f"refine_{attempt}"
                log.info(f"Validating run-tests.sh ({label})...")

                test_result = await run_test_script(
                    repo_path=repo_path,
                    run_tests_sh=repo_run_tests,
                    timeout=self.test_timeout,
                    log=log,
                )

                # Save validation result
                validation_file = phase_dir / f"validation_result_{label}.json"
                validation_file.write_text(
                    json.dumps(test_result, indent=2, ensure_ascii=False),
                    encoding="utf-8",
                )

                if test_result["exit_code"] == 0:
                    passed = test_result.get("passed", 0)
                    total = test_result.get("total", 0)
                    log.info(f"Test validation PASSED ({label}): {passed}/{total}")
                    return run_tests_path

                # Failed — if we still have refine budget, ask agent to fix
                if attempt < max_refine:
                    log.warning(f"Test validation failed ({label}), "
                                f"refining... ({attempt + 1}/{max_refine})")

                    # Truncate log to last 3000 chars to avoid overwhelming context
                    error_log = test_result.get("output", "")
                    if len(error_log) > 3000:
                        error_log = f"...(truncated)\n{error_log[-3000:]}"

                    refine_prompt = (
                        f"run-tests.sh 执行失败了，exit code: {test_result['exit_code']}。\n\n"
                        f"错误日志:\n```\n{error_log}\n```\n\n"
                        f"请分析错误原因，修改 run-tests.sh 使测试能通过。\n"
                        f"注意：只修改 run-tests.sh 的内容，不要修改仓库代码。\n\n"
                        f"输出修改后的完整 run-tests.sh：\n"
                        f"```json\n{{\"run_tests_sh\": \"...\"}}\n```"
                    )

                    refine_result = await executor.execute_with_json_retry(
                        query=refine_prompt,
                        continue_conversation=True,
                        timeout=25200,
                        max_retries=2,
                        must_include_keys=["run_tests_sh"],
                    )

                    if refine_result and refine_result.get("run_tests_sh"):
                        self._write_run_tests(
                            refine_result["run_tests_sh"],
                            run_tests_path, repo_run_tests, log,
                        )
                    else:
                        log.error("Refine failed to produce new run-tests.sh")
                        return None
                else:
                    log.error(f"Test validation failed after {max_refine} refine attempts")
                    return None

        except Exception as e:
            log.error(f"Phase 2 failed: {e}")
            return None
        finally:
            try:
                await executor.disconnect()
            except Exception:
                pass

        return None

    @staticmethod
    def _write_run_tests(
        content: str,
        output_path: Path,
        repo_path: Path,
        log: logging.Logger,
    ):
        """Write run-tests.sh to both output dir and repo dir."""
        output_path.write_text(content, encoding="utf-8")
        output_path.chmod(0o755)
        repo_path.write_text(content, encoding="utf-8")
        repo_path.chmod(0o755)
        log.info(f"Wrote run-tests.sh ({len(content)} chars)")


# ---------------------------------------------------------------------------
# Test execution utility
# ---------------------------------------------------------------------------

async def run_test_script(
    repo_path: Path,
    run_tests_sh: Path,
    timeout: int = 300,
    log: Optional[logging.Logger] = None,
) -> Dict:
    """
    Run the run-tests.sh script and parse results.

    Returns dict with: exit_code, output, passed, failed, total, pass_rate
    """
    log = log or logging.getLogger(__name__)

    result = {
        "exit_code": -1,
        "output": "",
        "passed": 0,
        "failed": 0,
        "error": 0,
        "total": 0,
        "pass_rate": 0.0,
    }

    # Clean previous result.json
    result_json_path = repo_path / "result.json"
    if result_json_path.exists():
        result_json_path.unlink()

    try:
        proc = subprocess.run(
            ["bash", str(run_tests_sh)],
            cwd=repo_path,
            capture_output=True,
            text=True,
            timeout=timeout,
            env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"},
        )
        result["exit_code"] = proc.returncode
        result["output"] = proc.stdout + proc.stderr

        log.info(f"Test exit code: {proc.returncode}")
        if proc.stdout:
            log.info(f"stdout (last 300): ...{proc.stdout[-300:]}")
        if proc.stderr:
            log.info(f"stderr (last 300): ...{proc.stderr[-300:]}")

    except subprocess.TimeoutExpired:
        result["exit_code"] = -1
        result["output"] = f"Timed out after {timeout}s"
        log.error(f"Test timed out after {timeout}s")
        return result
    except Exception as e:
        result["exit_code"] = -1
        result["output"] = str(e)
        log.error(f"Test execution failed: {e}")
        return result

    # Parse result.json if generated
    if result_json_path.exists():
        try:
            data = json.loads(result_json_path.read_text(encoding="utf-8"))
            result["passed"] = data.get("passed", 0)
            result["failed"] = data.get("failed", 0)
            result["error"] = data.get("error", 0)
            result["total"] = data.get("total", result["passed"] + result["failed"] + result["error"])
            if result["total"] > 0:
                result["pass_rate"] = result["passed"] / result["total"]
        except Exception as e:
            log.warning(f"Failed to parse result.json: {e}")

    # Fallback: parse from output
    if result["total"] == 0:
        parsed = _parse_test_output(result["output"], result["exit_code"])
        result.update(parsed)

    return result


def _parse_test_output(output: str, exit_code: int) -> Dict:
    """Fallback output parser (same logic as verilog_test_runner)."""
    import re

    # Try "N passed, N failed"
    passed_match = re.search(r"(\d+)\s+passed", output, re.IGNORECASE)
    failed_match = re.search(r"(\d+)\s+failed", output, re.IGNORECASE)
    if passed_match or failed_match:
        passed = int(passed_match.group(1)) if passed_match else 0
        failed = int(failed_match.group(1)) if failed_match else 0
        total = passed + failed
        if total > 0:
            return {
                "passed": passed, "failed": failed, "error": 0,
                "total": total, "pass_rate": passed / total,
            }

    # Try PASS/FAIL keywords
    pass_count = sum(1 for line in output.split("\n")
                     if re.search(r"\bPASS(?:ED)?\b", line.upper())
                     and "PASSWORD" not in line.upper())
    fail_count = sum(1 for line in output.split("\n")
                     if re.search(r"\bFAIL(?:ED)?\b", line.upper()))
    total = pass_count + fail_count
    if total > 0:
        return {
            "passed": pass_count, "failed": fail_count, "error": 0,
            "total": total, "pass_rate": pass_count / total,
        }

    # Fallback: exit code
    if exit_code == 0:
        return {"passed": 1, "failed": 0, "error": 0, "total": 1, "pass_rate": 1.0}
    return {"passed": 0, "failed": 1, "error": 0, "total": 1, "pass_rate": 0.0}
